//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AmVinDecoder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AmVinDecoder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ------------------------------------------------------------.
        /// </summary>
        internal static string HorizontalRule {
            get {
                return ResourceManager.GetString("HorizontalRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Body Type.
        /// </summary>
        internal static string Label_BodyType {
            get {
                return ResourceManager.GetString("Label_BodyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine.
        /// </summary>
        internal static string Label_Engine {
            get {
                return ResourceManager.GetString("Label_Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factory.
        /// </summary>
        internal static string Label_Factory {
            get {
                return ResourceManager.GetString("Label_Factory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Label_Model {
            get {
                return ResourceManager.GetString("Label_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model Year.
        /// </summary>
        internal static string Label_ModelYear {
            get {
                return ResourceManager.GetString("Label_ModelYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restraint System.
        /// </summary>
        internal static string Label_RestraintSystem {
            get {
                return ResourceManager.GetString("Label_RestraintSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Number.
        /// </summary>
        internal static string Label_SerialNumber {
            get {
                return ResourceManager.GetString("Label_SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmisson.
        /// </summary>
        internal static string Label_Transmisson {
            get {
                return ResourceManager.GetString("Label_Transmisson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN.
        /// </summary>
        internal static string Label_Vin {
            get {
                return ResourceManager.GetString("Label_Vin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to : .
        /// </summary>
        internal static string LabelSeperator {
            get {
                return ResourceManager.GetString("LabelSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN?.
        /// </summary>
        internal static string Prompt_Vin {
            get {
                return ResourceManager.GetString("Prompt_Vin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aston Martin VIN Decoder.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
