name: .NET Core

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v1
              with:
                  dotnet-version: "6.x"
            - name: Install dependencies
              run: dotnet restore src/AmVinDecoder.sln
            - name: Build
              run: dotnet build --configuration Release --no-restore src/AmVinDecoder.sln
            - name: Test
              run: dotnet test --no-restore --verbosity normal src/AmVinDecoder.sln
